### ISSUE TITLE
Create Main UI

### ISSUE THREAD

**Issue by jcesperanza** [NEU-SoftEng/thesesApp#7]

**Comment by PiaMacalanda** [comment]
**Modified Main UI Mock-up:**
You can view the modified design for the Main UI on [Figma](https://www.figma.com/design/24Q4YHtvL9s04PlbFZ3hWk/Library-UI?node-id=31-39&t=RRax4QkO1tEorjHN-1).

**Key Updates:**
- Improved user interface for better navigation.
- Modification of components and color palette.
- Enhanced visual appeal and readability.

Feel free to check it out and provide feedback
